### ISSUE TITLE
Render canvas in wasm 

### ISSUE THREAD

**Issue by sepiropht** [topheman/rust-wasm-experiments#3]
I have a question. What happen if you render the ui in wasm. Perf is better or not ? I'm asking that because in wasm-bindgen repos there is some example like this  [https://rustwasm.github.io/wasm-bindgen/examples/paint.html](https://rustwasm.github.io/wasm-bindgen/examples/paint.html)

**Comment by topheman** [comment]
Hie @sepiropht ,

I just setup the ball rendering in wasm : https://github.com/topheman/rust-wasm-experiments/commit/55b1ed48d70a865ab1e44e208e64f69bb55c3de2 .

Even when changing ball radius / number of balls, the perfs are quite the same.

The next step is to maintain a Vector of Balls on the WASM side (not on the JavaScript side), that way, the iterations and memory accesses will be better (less round trips between JS ans WASM).

**Comment by sepiropht** [comment]
I'm very curious to see how you gonna make it work in rust.
 
I tried very hard to make iteration in wasm works. You could check, i cloned your repo.

The hardest thing is the update_balls logic in rust where you have to mutate the same collection twice.
I tried many things (Clone, RefCell..). 
Finally compile and build success but, i get an error in console
